---
title: "Causal inference for time-to-event outcomes -- with practical applications in R"
subtitle: "One-day pre-conference course at the Conference of the International Society for Clinical Biostatistics in Freiburg, September 27, 2026"
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

---

### Course overview

Recent years have seen major developments in methods for causal inference using observational data. However, the practical application of the methods is challenging and lags behind methodological developments. This is especially true in the context of survival and other time-to-event outcomes, which are commonly of interest in applications in biostatistics and data science. 

This course will provide training on concepts and methods for estimating causal effects of treatments on time-to-event outcomes. It will begin with an introduction to causal estimands and assumptions required for their identification using observational data. It will then cover estimation methods for confounding adjustment, including inverse probability weighting, marginal structural models, g-formula, and censoring-weighting approaches. The initial focus will be on treatments given at a single time point, before extending to time-varying treatment strategies. Methods that incorporate machine learning methods will be included, and extensions to settings with competing events will also be discussed. 

The course material will be presented with medical and epidemiological applications in mind, but the methods are equally relevant in other areas, such as social science and economics. The course will combine lectures and computer practical sessions using openly accessible data sets.

More details about the course, including location, can be found [at the NBBC web pages](https://iscbgmds2026.info/pre-conference-courses/#2){target="_blank"}. For an updated program, see [here](program.html).

---

### Course tutors

[Ruth Keogh](https://www.lshtm.ac.uk/aboutus/people/keogh.ruth){target="_blank"}, Professor at the London School of Hygiene & Tropical Medicine.

[Jon Michael Gran](https://www.med.uio.no/imb/english/people/aca/jonmic/index.html){target="_blank"}, Professor at the University of Oslo.

---

### Contact and further information

For questions about the course please contact the course tutors by email on  ruth.keogh "at" lshtm.ac.uk or j.m.gran "at" medisin.uio.no. For practical questions, such as registration etc, contact the conference organisers through the web pages of the [Conference of the International Society for Clinical Biostatistics (ISCB)](https://iscbgmds2026.info){target="_blank"}.

</br>
