---
title: "Program"
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

---

All times are in CEST.

**Part 1: Introduction and estimation of the effects of point treatments on survival**

|Time                 |Topic                                                                                         |Tutor                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|08:30 - 09:15        |Lecture 1: Causal estimands for time-to-event outcomes and identification using observational data | Jon Michael Gran                       |                       |
|09:15 - 10:00        |Lecture 2: Estimating the effects of point treatments | Ruth Keogh                         |
|10:00 - 10:30        |R practical 1: Methods for point treatments | Jon Michael Gran                           |
|*10:30 - 11:00*      |*Break* | 
|11:00 - 11:45        |R practical 1 (cont.) | Jon Michael Gran                           |

**Part 2: Extensions to time-dependent treatment strategies**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|11:45 - 12:30        |Lecture 3: Methods for time-dependent treatment strategies  | Jon Michael Gran                           |
|*12:30 - 13:30*        |*Lunch* |                           |
|13:30 - 14:15        |R practical 2: Methods for time-dependent treatment strategies | Ruth Keogh                           |
|14:15 - 15:00        |Lecture 4: Doubly robust methods | Ruth Keogh                         |
|*15:00 - 15:30*        |*Break*  |                        |
|15:30 - 16:30        |R practical 3: Doubly robust methods  | Ruth Keogh                         |
|16:30 - 17:00        |Closure |                         |
</br>
